### ISSUE TITLE
WM_LABEL_SIZE metis 5.1.0 did not build clang: error: linker... 

### ISSUE THREAD

**Issue by ajl42** [mrklein/openfoam-os-x#19]
Hi, thanks for all the great work with openFOAM, Mac os x and home-brew.  It is very impressive and helped my work.  I've installed home-brew and openFOAM 3.0.0 on my macbook pro ( El-Cap)  and it runs happily in serial.  So I've just tried to update metis and scotch as per:

https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM-3.0.(0%7Cx)-&-WM_LABEL_SIZE=64

via:

$ brew install https://raw.githubusercontent.com/mrklein/openfoam-os-x/master/formulae/metis64.rb

and it fails, I'm not sure why.  Can you please help, attached is the output of above script:

[log.metis64.zip](https://github.com/mrklein/openfoam-os-x/files/219351/log.metis64.zip)

Many thanks,  Andy

**Comment by mrklein** [comment]
Hi,

Installation fails due to the bug in LLVM which comes with Xcode 7.3 (https://llvm.org/bugs/show_bug.cgi?id=27059).

I have pushes workaround base upon upstream METIS formula (https://github.com/Homebrew/homebrew-science/blob/master/metis.rb). Now it builds without error, at least on my OS X 10.11.4/clang-703.0.29.

**Comment by ajl42** [comment]
Hi, thanks for the work around.  Really appreciate the support.

Andy.
