### ISSUE TITLE
__ZN4FoamlsERNS_7OstreamEl Symbol not Found?

### ISSUE THREAD

**Issue by APCoding** [mrklein/openfoam-os-x#25]
Hi,

I seem to have another problem. I can't run icoFoam on the cavity tutorial, and it throws this error:
`dyld: Symbol not found: __ZN4FoamlsERNS_7OstreamEl
  Referenced from: /Users/PeterE/OpenFOAM/OpenFOAM-4.0/platforms/darwin64ClangDPInt32Opt/bin/icoFoam
  Expected in: flat namespace`

This seems to be the same error as [this person](http://www.cfd-online.com/Forums/openfoam-installation-windows-mac/166356-installing-openfoam-3-0-x-mac-os-x-homebrew.html) had, but your fix of changing `motionSolverLibs ( "libfvMotionSolvers.so" );` to `.dylib`. It didn't work, throwing the same error (I was using `movingCone`):
`dyld: Symbol not found: __ZN4FoamlsERNS_7OstreamEl
  Referenced from: /Users/PeterE/OpenFOAM/OpenFOAM-4.0/platforms/darwin64ClangDPInt32Opt/bin/pimpleDyMFoam
  Expected in: flat namespace`
The whole output is [here](http://pastebin.com/WSkeudtU).

Even if I get `movingCone` to work, is there a way to fix this for all simulations to come?
Thank you so much, and I'm sorry to bug you with these issues.

**Comment by mrklein** [comment]
This one is caused by third party `cpp`, which does not define `__clang__` and `__APPLE__` symbols (you can check it with command `cpp -dD /dev/null | grep -E '(__clang__|__APPLE__)'`). As a result this part of `src/OpenFOAM/Make/files`:

```
#if defined(__APPLE__) && defined(__clang__)
$(ints)/long/long.C
$(ints)/long/longIO.C
$(ints)/ulong/ulong.C
$(ints)/ulong/ulongIO.C
#endif
```

is lost and you have missing symbols error.

Solution is similar to `flex` one:

1. Uninstall third party `cpp`.
2. Remove third party `cpp` from `PATH` for the time of compilation.
3. Open `src/OpenFOAM/Make/files`, comment out line `#if defined(__APPLE__) && defined(__clang__)` and `#endif` after it (or just remove these lines).
4. Open `wmake/rules/General/general` file and change `CPP        = cpp` to `CPP        = xcrun cpp`.

After corrections you have to recompile libOpenFOAM (either run `wmake` in `src/OpenFOAM`, or just run global `Allwmake` script).

P.S. there is no need to change `.so` to `.dylib` in dictionaries, patched `Foam::dlOpen` looks for file with `dylib` extension if it was not able to find one with `so` extension.

**Comment by APCoding** [comment]
OK! Thanks! `icoFoam` works now! If I have any more issues, I'll make sure to check if it's a third party problem. Thank you for your patience.
