### ISSUE TITLE
Failure of parmetis install unable to download resource

### ISSUE THREAD

**Issue by ajl42** [mrklein/openfoam-os-x#27]
Hi, thanks for all the good work, I've obtained the following error when installing parmetis using brew.  Any ideas what is wrong?

Thanks,

Andy.

curl: (52) Empty reply from server
Error: Failed to download resource "parmetis"
Download failed: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz

**Comment by mrklein** [comment]
Well, strictly speaking this is an issue with brew and parMETIS not with OpenFOAM patches ;)

And about what is wrong: there could be global problem with U. Minnesota servers (though it is not a case, since umn.edu opens), there could be U. Minnesota infrastructure update and in a few days download URL in formula will be updated, there could be general loss of interest in parMETIS, so author abandoned the project (doubt it).

You can

1. Build OpenFOAM without parMETIS.
2. File bug report in Homebrew repository.
3. Wait till problem resolves itself.

**Comment by ajl42** [comment]
Hi Alexey,

                 thanks, sorry I realised after I’d post the issue that it was a Brew problem.  I’ll wait
and see if things fix themselves.  I’ll build OpenFOAM without parMETIS at the same time 

Thanks for the mac OS installation using brew what you’re doing is ideal and makes my 
life a lot easier!

Best wishes,

Andy.

**Comment by mrklein** [comment]
Thanks. Can we close the issue?

**Comment by ajl42** [comment]
Yes of course.  Thanks.

Andy.

**Comment by hadisfr** [comment]
> parmetis cannot be incorporated into homebrew right now, it requires patches to be built. Given the last version was released 5 years ago, I am doubtful development is ongoing :(
https://github.com/Homebrew/homebrew-core/issues/22660#issuecomment-356394498

Could you please update the wiki (https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM(R)-release-&-Homebrew) please @mrklein ?

**Comment by mrklein** [comment]
OK. Done.
