### ISSUE TITLE
The OpenFOAM-dev commit history has been changed.

### ISSUE THREAD

**Issue by AleksZhuravlyov** [mrklein/openfoam-os-x#48]
A patch for OpenFOAM-7 points on the commit 0ebbff061 but apparently developers have done some rebase and now hash for those commit is 4e902bf45.

**Comment by mrklein** [comment]
Hi Aleksandr,

Is it a request for update?

Since OpenFOAM uses rolling releases scheme, OpenFOAM-7 repository receives constant updates, so latest commit checksum changes from time to time. 4 months ago master was at 0ebbff061, now it is at 4e902bf45. With high probability old patch can be applied to the current state of the repository.

Contrary, OpenFOAM-dev repository is at b22545b and dev-branch patch can not be applied to the current source tree.

Checksum part of the patch file name does not point anywhere. It is just a reference to the state of the source tree, when the patch was created.

**Comment by AleksZhuravlyov** [comment]
Hi, Alexey.

Thanks for the clarification.

It is not a request for update, I've just messed a bit following "OpenFOAM(R) dev & Homebrew" guide. Pointing 4e902bf45 instead of 0ebbff061 works properly.
